---EMPLOYEE AUDIT TRIGGER SYSTEM
--Implemented database triggers to track INSERT,UPDATE,and DELETE operations
--Designed audit tables to maintain historical data changes
--Ensured automatic logging of employees salary updates.

---Create Employees Table
CREATE TABLE employees(
  emp_id NUMBER PRIMARY KEY,
  emp_name VARCHAR2(50),
  salary NUMBER,
  department VARCHAR2(50)
);

---Create Audit Table
CREATE TABLE employee_audit(
  audit_id NUMBER GENERATED BY DEFAULT
AS IDENTITY,
  emp_id NUMBER,
  action_type VARCHAR2(10),
  old_salary NUMBER,
  new_salary NUMBER,
  changed_date DATE
);

--BEFORE INSERT Trigger(when a new employee is inserted, the trigger logs it)
CREATE OR REPLACE TRIGGER trg_emp_insert
BEFORE INSERT ON employees
FOR EACH ROW
BEGIN
    INSERT INTO employee_audit(emp_id,
action_type,new_salary,changed_date)
    VALUES(:NEW.emp_id,
'INSERT',:NEW.salary,SYSDATE);
END;
/

--AFTER UPDATE Trigger(This trigger records salary changes)
CREATE OR REPLACE TRIGGER trg_emp_update
AFTER UPDATE ON employees
FOR EACH ROW
BEGIN
    INSERT INTO employee_audit(emp_id,
action_type,old_salary,new_salary,changed_date)
    VALUES(:OLD.emp_id,
'UPDATE',:OLD_salary,:NEW.salary,SYSDATE);
END;
/

--BEFORE DELETE Trigger(Logs when an employee is removed)
CREATE OR REPLACE TRIGGER trg_emp_delete
BEFORE DELETE ON employees
FOR EACH ROW
BEGIN
    INSERT INTO employee_audit(emp_id,
action_type,old_salary,changed_date)
    VALUES(:OLD.emp_id,
'DELETE',:OLD.salary,SYSDATE);
END;
/

---TEST the Trigger(Insert Employee)
INSERT INTO employees VALUES
(1,'chandana',50000,'IT');
--Update Salary
UPDATE employees SET salary = 60000 WHERE emp_id=1;
--Delete Employee
DELETE FROM employees WHERE emp_id=1;


----Check Audit Logs
SELECT * FROM employee_audit;


























